name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check_code_quality:
    name: Check code quality
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build and verify no warnings or errors
      run: |
        cargo rustc --lib -- -D warnings
        cargo rustc --bin rust-obj-terminal-viewer -- -D warnings
    - name: Run tests
      run: cargo test
    - name: Check code formatting
      run: cargo fmt --check
